version: "3"

services:
  alarm:
    build: ./src
    ports:
      - 7000:7000
    depends_on:
      - kafka
      - notification

  notification:
    build: ./services/notification
    depends_on:
      - whatsapp
      - telegram
      - sms

  whatsapp:
    build: ./services/whatsapp
    depends_on:
      - kafka
    deploy:
      mode: replicated
      replicas: 2

  sms:
    build: ./services/sms
    depends_on:
      - kafka

  telegram:
    build: ./services/telegram
    depends_on:
      - kafka

  zookeeper:
    image: bitnami/zookeeper:3.8
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.2
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
